此notebook素材来自kesci.com两个练习系列.
* [Numpy快速上手指南 --- 基础篇](https://www.kesci.com/home/project/59ed832d18ec724555a9a968)

# 数据大小

## 定义

* axes: 轴
* rank: 秩

例如:
[[ 1., 0., 0.], [ 0., 1., 2.]] 的axes维度为2, 第一个维度rank2, 第二个维度rank3

In [3]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 查看维度(dimension)

In [5]:
a.shape

(3, 5)

## 查看多少个轴

In [8]:
a.ndim

2

## 查看数据类型

In [10]:
a.dtype

dtype('int32')

In [11]:
a.dtype.name

'int32'

## 每个元素的字节大小

In [12]:
a.itemsize

4

## 总个数

In [13]:
a.size

15

## 类型

In [14]:
type(a)

numpy.ndarray

# 数组创建

## list创建

In [19]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [21]:
a.dtype

dtype('int32')

In [24]:
a = np.array([(1.5,2,3),(4,5,6)])
a

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
a.dtype

dtype('float64')

**指定数据类型**创建

In [29]:
a = np.array([[1,2],[3,4]], dtype=complex )
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [31]:
a.dtype

dtype('complex128')

In [32]:
a.itemsize

16

## 内置函数创建

通常，数组的元素开始都是未知的，但是它的大小已知。因此，Numpy提供了一些使用占位符创建数组的函数。这最小化了扩展数组的需要和高昂的运算代价。

### 全0数组

In [35]:
np.zeros((3,4),dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

按变量shape创建

In [51]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [52]:
np.zeros_like(a)

array([0, 0, 0])

### 全1数组

In [37]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

按变量shape创建

In [51]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [62]:
np.ones_like(a)

array([1, 1, 1])

### 空数组

In [45]:
np.empty((2,5))

array([[1.37700972e-311, 2.32210854e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 7.52736939e+252, 2.09570572e-110,
        2.91237123e+257, 4.71294503e+257]])

### 等间隔数列

aranga定义间隔大小

In [46]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [47]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

linspace定义总共多少间隔

In [70]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

###  随机数

纯随机

In [74]:
np.random.rand(2,3)

array([[0.80722577, 0.64305952, 0.22218733],
       [0.32297689, 0.46138349, 0.18416854]])

标准正态分布随机

In [79]:
np.random.randn(2,3)

array([[ 2.65856467,  1.35871691, -0.13102211],
       [ 0.212424  , -0.87073905,  0.83563459]])

一般正态分布随机

In [83]:
np.random.normal(loc=1,scale=0.5,size=(2,3))

array([[0.52176134, 1.02691187, 1.37880997],
       [1.19657311, 1.31502553, 0.38417858]])

自定义离散总体及样本概率分布的随机

In [85]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['pooh', 'pooh', 'pooh', 'Christopher', 'Christopher'], dtype='<U11')

整数随机

In [95]:
np.random.randint(low=-2,high=10,size=10)

array([0, 5, 8, 0, 9, 7, 3, 5, 2, 2])